(function(){
  const INTERNAL=new URLSearchParams(location.search).get('interno')==='1';
  if(!INTERNAL)return;

  function injectFenixStyles(){
    if(document.getElementById('fenix-pipeline-theme'))return;
    const style=document.createElement('style');
    style.id='fenix-pipeline-theme';
    style.textContent=`
      body{background:radial-gradient(circle at 80% 0,rgba(211,151,31,.09),transparent 28%),#050505!important;color:#f7f2e8!important}
      body>.top{display:none!important}.wrap{max-width:1540px!important;padding-top:28px!important}
      #fenix-internal-dashboard{position:relative;overflow:hidden;background:linear-gradient(145deg,#090909,#0c0b08)!important;border:1px solid #5b431b!important;box-shadow:0 18px 55px rgba(0,0,0,.38)!important;color:#f7f2e8!important;border-radius:22px!important;padding:26px!important}
      #fenix-internal-dashboard:after{content:"";position:absolute;right:-95px;top:-70px;width:430px;height:430px;background:url('/assets/fenix-symbol.png') center/contain no-repeat;opacity:.045;filter:grayscale(1) brightness(.75);pointer-events:none}
      .fenix-pipeline-head{position:relative;z-index:2;display:grid;grid-template-columns:minmax(360px,1fr) auto;gap:28px;align-items:center;margin-bottom:22px;padding-bottom:20px;border-bottom:1px solid #3e3017}.fenix-pipeline-logo{width:320px;height:86px;background:url('/assets/fenix-logo-transparent.webp') left center/contain no-repeat}.fenix-pipeline-title{font-size:25px;font-weight:950;letter-spacing:.07em;color:#f1c04d;text-transform:uppercase;margin-top:3px}.fenix-pipeline-sub{font-size:14px;color:#bbb2a3;margin-top:6px;line-height:1.5;max-width:800px}.fenix-pipeline-actions{display:flex;gap:9px;flex-wrap:wrap;justify-content:flex-end}.fenix-pipeline-action{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 14px;border-radius:11px;border:1px solid #624a20;background:#12100b;color:#f5d36b;text-decoration:none;font-size:12px;font-weight:850;cursor:pointer}.fenix-pipeline-action.primary{background:linear-gradient(180deg,#f1c04d,#b97810);color:#111;border:0}
      .fenix-metrics-grid{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:20px}.fenix-metric{background:linear-gradient(180deg,#15130e,#0b0b0b);border:1px solid #49391d;border-radius:15px;padding:15px 16px}.fenix-metric span{display:block;color:#aaa18f;font-size:11px;text-transform:uppercase;letter-spacing:.08em}.fenix-metric strong{display:block;color:#f3c550;font-size:24px;margin-top:5px}
      .fenix-stage-row{position:relative;z-index:2;display:grid;grid-template-columns:repeat(6,minmax(260px,1fr));gap:12px;overflow-x:auto;padding:2px 2px 10px}.fenix-stage{background:#0d0d0c;border:1px solid #3d311c;border-radius:16px;padding:12px;min-height:330px}.fenix-stage[data-stage="encerrado"]{border-color:#3a342d;background:#0a0a0a}.fenix-stage.drag-over{outline:2px solid #dca82f;outline-offset:2px}.fenix-stage-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px;padding-bottom:9px;border-bottom:1px solid #2d281e}.fenix-stage-title{font-size:14px;font-weight:900;color:#f3ca58}.fenix-stage-hint{font-size:11px;color:#948c7f;line-height:1.35;margin-top:4px;min-height:30px}.fenix-count{min-width:28px;height:28px;border-radius:999px;display:grid;place-items:center;background:#342b18;color:#f5d36b;font-size:11px;font-weight:900}.fenix-cardlist{display:grid;gap:10px;margin-top:10px}.fenix-card{background:linear-gradient(180deg,#171714,#0b0b0b);border:1px solid #4a391d;border-radius:13px;padding:14px;box-shadow:0 5px 16px rgba(0,0,0,.25);cursor:grab}.fenix-card:active{cursor:grabbing}.fenix-card.closed{opacity:.72;border-color:#39342d}.fenix-card-name{font-size:13px;line-height:1.28;color:#f8f2e7;font-weight:900;min-height:34px}.fenix-card-meta{font-size:10px;color:#9e9689;margin-top:6px}.fenix-card-money{margin-top:10px;padding-top:9px;border-top:1px solid #302919}.fenix-card-money span{display:block;font-size:10px;color:#968e80}.fenix-card-money strong{font-size:16px;color:#f3c550}.fenix-card-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:11px}.fenix-card-btn,.fenix-card-link{border:1px solid #6a5021;background:#17140e;color:#f5d36b;border-radius:9px;padding:8px 10px;font-size:11px;font-weight:800;text-decoration:none;cursor:pointer}.fenix-card-btn.close{border-color:#4a4134;color:#cfc6b7;background:#111}.fenix-card-btn.reopen{border-color:#47604b;color:#c9edcd;background:#0d1710}.fenix-empty{font-size:11px;color:#817b71;padding:12px 3px}.fenix-rule-note{position:relative;z-index:2;margin-top:12px;color:#8f877a;font-size:11px;line-height:1.45}.fenix-rule-note b{color:#d7b45a}
      @media(max-width:900px){.wrap{padding:12px!important}#fenix-internal-dashboard{padding:16px!important}.fenix-pipeline-head{grid-template-columns:1fr}.fenix-pipeline-logo{width:250px;height:68px}.fenix-pipeline-actions{justify-content:flex-start}.fenix-metrics-grid{grid-template-columns:1fr 1fr}.fenix-stage-row{grid-template-columns:repeat(6,minmax(245px,270px))}}
    `;
    document.head.appendChild(style);
  }
  injectFenixStyles();

  const STAGES=[
    {key:'entrada',title:'Entrada',hint:'Novos levantamentos recebidos'},
    {key:'cfo',title:'Análise CFO',hint:'Rascunho e definição comercial'},
    {key:'proposta',title:'Proposta',hint:'Aprovada ou publicada ao cliente'},
    {key:'aceite',title:'Aceite',hint:'Cliente aceitou · aguardando CFO'},
    {key:'contrato',title:'Contrato',hint:'Autorizado para geração/assinatura'},
    {key:'encerrado',title:'Encerrado',hint:'Oportunidades fechadas ou sem continuidade'}
  ];
  const STATUS={recebido:'Recebido',em_analise_cfo:'Rascunho CFO',rascunho_cfo:'Rascunho CFO',aprovada_cfo:'Aprovada CFO',publicada:'Publicada',proposta_aceita_aguardando_cfo:'Aceita · aguardando CFO',contrato_autorizado:'Contrato autorizado',encerrado:'Encerrado'};
  const RANK={entrada:1,cfo:2,proposta:3,aceite:4,contrato:5,encerrado:0};
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}
  function statusOf(item,p){if(item?.status==='encerrado')return'encerrado';if(item?.status==='contrato_autorizado')return'contrato_autorizado';if(item?.status==='proposta_aceita_aguardando_cfo')return'proposta_aceita_aguardando_cfo';if(p?.status==='publicada')return'publicada';if(p?.status==='aprovada_cfo')return'aprovada_cfo';if(p?.status==='em_analise_cfo'||p?.status==='rascunho_cfo')return'em_analise_cfo';return'recebido'}
  function stageOf(status){if(status==='encerrado')return'encerrado';if(status==='contrato_autorizado')return'contrato';if(status==='proposta_aceita_aguardando_cfo')return'aceite';if(status==='publicada'||status==='aprovada_cfo')return'proposta';if(status==='em_analise_cfo'||status==='rascunho_cfo')return'cfo';return'entrada'}
  function proposalUrl(p){if(p?.public_slug)return`/p/proposta-master-v1.html?ref=${encodeURIComponent(p.public_slug)}`;return p?.public_url||''}
  function currentTime(x){return new Date(x.p?.updated_at||x.p?.published_at||x.item?.updated_at||x.item?.created_at||0).getTime()||0}
  function opportunityKey(x){const cnpj=String(x.item?.client?.cnpj||'').replace(/\D/g,'');return cnpj||x.item?.client_id||x.item?.id}
  function dedupe(cards){
    const chosen=new Map();
    for(const x of cards){
      const key=opportunityKey(x),prev=chosen.get(key);if(!prev){chosen.set(key,x);continue}
      const activeX=x.stage!=='encerrado',activeP=prev.stage!=='encerrado';
      if(activeX&&!activeP){chosen.set(key,x);continue}if(!activeX&&activeP)continue;
      const rankX=RANK[x.stage]||0,rankP=RANK[prev.stage]||0;
      if(rankX>rankP||(rankX===rankP&&currentTime(x)>currentTime(prev)))chosen.set(key,x);
    }
    return [...chosen.values()].sort((a,b)=>currentTime(b)-currentTime(a));
  }
  function hideAnalysisUntilOpen(){const dashboard=document.getElementById('fenix-internal-dashboard');if(!dashboard)return;[...document.querySelectorAll('.wrap > .card')].forEach(card=>{if(card!==dashboard&&!card.id?.startsWith('fenix-internal-login'))card.style.display='none'});document.getElementById('diagnostico')?.classList.add('hidden')}
  function showAnalysis(){const dashboard=document.getElementById('fenix-internal-dashboard');[...document.querySelectorAll('.wrap > .card')].forEach(card=>{if(card!==dashboard)card.style.display=''})}
  async function setOpportunityStage(intakeId,action){const verb=action==='close'?'encerrar esta oportunidade':'reabrir esta oportunidade';if(!confirm(`Confirma ${verb}?`))return false;const r=await fetch('/api/internal-intake-stage',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({intake_id:intakeId,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível atualizar a oportunidade.');return true}

  async function enhance(){
    if(!window.FENIX_INTERNAL_MODE)return;const box=document.getElementById('fenix-internal-dashboard');if(!box||box.dataset.kanban==='1')return;
    try{
      const originalButtons=[...box.querySelectorAll('[data-open-intake]')],openHandlers=originalButtons.map(btn=>btn.onclick);
      const r=await fetch('/api/internal-intakes',{credentials:'same-origin'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar.');const items=d.items||[];
      const rawCards=items.map((item,idx)=>{const c=item.client||{},p=item.proposal||null,t=p?.commercial_terms||{},status=statusOf(item,p);return{item,idx,name:c.razao_social||c.nome_fantasia||'Cliente sem nome',status,stage:stageOf(status),date:item.created_at?new Date(item.created_at).toLocaleDateString('pt-BR'):'',mrr:Number(t.final_monthly||0),p,t}});
      const cards=dedupe(rawCards),active=cards.filter(x=>x.stage!=='encerrado');
      const pipelineMrr=active.filter(x=>x.stage!=='entrada').reduce((s,x)=>s+x.mrr,0),publishedMrr=active.filter(x=>['proposta','aceite','contrato'].includes(x.stage)).reduce((s,x)=>s+x.mrr,0),pendingCfo=active.filter(x=>x.stage==='cfo'||x.stage==='aceite').length;
      const cols=STAGES.map(stage=>{
        const list=cards.filter(x=>x.stage===stage.key);
        const html=list.map(x=>{const url=proposalUrl(x.p),action=x.stage==='cfo'?'Continuar análise':x.stage==='entrada'?'Abrir análise CFO':x.stage==='aceite'?'Revisar aceite':'Abrir análise';const main=x.stage==='encerrado'?`<button class="fenix-card-btn reopen" data-reopen="${x.item.id}">Reabrir</button>`:`<button class="fenix-card-btn" data-kanban-open="${x.idx}">${esc(action)}</button>`;const proposal=url&&x.stage!=='encerrado'?`<a class="fenix-card-link" href="${esc(url)}" target="_blank" rel="noopener">Proposta oficial ↗</a>`:'';const close=x.stage!=='encerrado'?`<button class="fenix-card-btn close" data-close="${x.item.id}">Encerrar</button>`:'';return`<article class="fenix-card ${x.stage==='encerrado'?'closed':''}" draggable="${x.stage!=='encerrado'}" data-intake-id="${esc(x.item.id)}"><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><div class="fenix-card-name">${esc(x.name)}</div><span style="font-size:9px;padding:5px 7px;border-radius:999px;background:#292319;color:#e8c96d;font-weight:800;white-space:nowrap">${esc(STATUS[x.status]||'Recebido')}${x.p?.version?` · v${x.p.version}`:''}</span></div><div class="fenix-card-meta">${esc(x.item.client?.cnpj||'')} · ${esc(x.date)}</div>${x.p?`<div class="fenix-card-money"><span>Mensalidade CFO</span><strong>${money(x.mrr)}</strong></div>`:''}<div class="fenix-card-actions">${main}${proposal}${close}</div></article>`}).join('')||'<div class="fenix-empty">Nenhum cliente nesta etapa.</div>';
        return`<section class="fenix-stage" data-stage="${stage.key}"><div class="fenix-stage-head"><div><div class="fenix-stage-title">${stage.title}</div><div class="fenix-stage-hint">${stage.hint}</div></div><span class="fenix-count">${list.length}</span></div><div class="fenix-cardlist">${html}</div></section>`
      }).join('');
      box.dataset.kanban='1';box.innerHTML=`<div class="fenix-pipeline-head"><div><div class="fenix-pipeline-logo" aria-label="FÊNIX Intelligent BPO"></div><div class="fenix-pipeline-title">Painel Comercial · Pipeline</div><div class="fenix-pipeline-sub">Uma oportunidade ativa por CNPJ. Levantamentos anteriores permanecem no histórico, sem duplicar o funil comercial.</div></div><div class="fenix-pipeline-actions"><a class="fenix-pipeline-action primary" href="/dados/" target="_blank" rel="noopener">Nova coleta</a><button class="fenix-pipeline-action" id="fenixCopyCollect">Copiar link da coleta</button><a class="fenix-pipeline-action" href="/atalhos/">Central de atalhos</a></div></div><div class="fenix-metrics-grid"><div class="fenix-metric"><span>Oportunidades ativas</span><strong>${active.length}</strong></div><div class="fenix-metric"><span>MRR em pipeline</span><strong>${money(pipelineMrr)}</strong></div><div class="fenix-metric"><span>MRR com proposta aprovada/publicada</span><strong>${money(publishedMrr)}</strong></div><div class="fenix-metric"><span>Ações CFO pendentes</span><strong>${pendingCfo}</strong></div></div><div class="fenix-stage-row">${cols}</div><div class="fenix-rule-note"><b>Governança:</b> Entrada → CFO → Proposta → Aceite → Contrato é automático. A movimentação manual é permitida somente para <b>Encerrado</b> e <b>Reabrir</b>.</div>`;
      const copyBtn=document.getElementById('fenixCopyCollect');if(copyBtn)copyBtn.onclick=async()=>{try{await navigator.clipboard.writeText('https://proposta.fenixbpo.com.br/dados/');const old=copyBtn.textContent;copyBtn.textContent='Link copiado ✓';setTimeout(()=>copyBtn.textContent=old,1800)}catch{copyBtn.textContent='proposta.fenixbpo.com.br/dados/'}};
      box.querySelectorAll('[data-kanban-open]').forEach(btn=>btn.onclick=()=>{const idx=Number(btn.dataset.kanbanOpen);showAnalysis();if(typeof openHandlers[idx]==='function'){openHandlers[idx].call(originalButtons[idx]);return}location.reload()});
      box.querySelectorAll('[data-close]').forEach(btn=>btn.onclick=async()=>{try{if(await setOpportunityStage(btn.dataset.close,'close'))location.reload()}catch(e){alert(e.message)}});
      box.querySelectorAll('[data-reopen]').forEach(btn=>btn.onclick=async()=>{try{if(await setOpportunityStage(btn.dataset.reopen,'reopen'))location.reload()}catch(e){alert(e.message)}});
      let dragged=null;box.querySelectorAll('.fenix-card[draggable="true"]').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card.dataset.intakeId});card.addEventListener('dragend',()=>{dragged=null;box.querySelectorAll('.fenix-stage').forEach(s=>s.classList.remove('drag-over'))})});
      const closed=box.querySelector('.fenix-stage[data-stage="encerrado"]');if(closed){closed.addEventListener('dragover',e=>{if(!dragged)return;e.preventDefault();closed.classList.add('drag-over')});closed.addEventListener('dragleave',()=>closed.classList.remove('drag-over'));closed.addEventListener('drop',async e=>{e.preventDefault();closed.classList.remove('drag-over');if(!dragged)return;try{if(await setOpportunityStage(dragged,'close'))location.reload()}catch(err){alert(err.message)}})}
    }catch(e){console.error('Kanban enhance:',e)}
  }
  const obs=new MutationObserver(()=>{const box=document.getElementById('fenix-internal-dashboard');if(box&&box.dataset.kanban!=='1'&&!box.dataset.kanbanScheduled){box.dataset.kanbanScheduled='1';setTimeout(()=>{hideAnalysisUntilOpen();enhance()},80)}});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('fenix:internal-authenticated',()=>setTimeout(()=>{hideAnalysisUntilOpen();enhance()},120));
})();
