const fallbackData={isDemo:true,clientName:'Cliente Demonstração',date:'26 de agosto de 2026',businessSummary:'Operação com rotinas administrativo-financeiras que precisam de mais organização, previsibilidade e informação gerencial para apoiar decisões.',diagnosticPhrase:'Organizar a rotina, reduzir retrabalho e transformar dados financeiros em informação útil para a gestão.',painPoints:['Retrabalho em lançamentos e conciliações','Informações dispersas em sistemas e planilhas','Baixa previsibilidade de caixa'],objectives:['Organização','Previsibilidade','Decisão'],operationalScope:[{title:'Conciliação bancária diária',description:'Conferência de movimentações e apontamento de divergências.'},{title:'Contas a pagar',description:'Organização e acompanhamento de títulos e documentos.'},{title:'Contas a receber',description:'Acompanhamento de recebimentos e pendências.'},{title:'Agendamentos',description:'Preparação conforme autorização do cliente.'}],strategicScope:[{title:'Fluxo de caixa',description:'Visão prevista e realizada para apoio à decisão.'},{title:'Relatório mensal',description:'Síntese executiva da operação e dos principais pontos de atenção.'},{title:'Reunião estratégica',description:'Encontro periódico para leitura dos dados e alinhamento.'}],technologyHighlights:['Processos','Automação','IA','Dados'],implementationSteps:['Diagnóstico','Parametrização','Organização inicial','Início da operação'],monthlyMovements:'Até 300/mês',cnpjs:'1 CNPJ',banks:'2 bancos',cards:'Até 3 cartões',contractsPerMonth:'Conforme escopo',commissionsPerMonth:'Conforme escopo',implementationSituation:'Operação parcialmente organizada',monthlyFee:'R$ 1.600,00',implementationFee:'R$ 1.500,00',softwareRepasse:'Conforme contratação',commercialConditions:['Valores consideram as premissas apresentadas nesta proposta.','Mudanças relevantes de volume, estrutura ou escopo podem gerar revisão comercial mediante alinhamento prévio.','Serviços extraordinários e retrabalhos fora do escopo somente serão executados após autorização do cliente.'],nextSteps:['Aprovação da proposta','Contrato','Kickoff e implantação','Início da operação']};
const d=window.__FENIX_PROPOSAL_DATA__||fallbackData;
const q=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const setText=(id,v)=>{const el=q(id);if(el)el.textContent=v??''};
const setHtml=(id,v)=>{const el=q(id);if(el)el.innerHTML=v??''};
function list(items,cls='scopeItem'){return(items||[]).map(x=>typeof x==='string'?`<div class="${cls}"><strong>${esc(x)}</strong></div>`:`<div class="${cls}"><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p></div>`).join('')}
function addBillingSummary(){const conditions=q('conditions');if(!conditions)return;const box=conditions.closest('.legalBox');if(!box||box.querySelector('.billingWrap'))return;const wrap=document.createElement('div');wrap.className='billingWrap';wrap.innerHTML=`<h4>Forma de cobrança</h4><div class="billingGrid"><div class="billingItem"><span>Mensalidade</span><strong>${esc(d.monthlyFee||'Conforme contrato')} — cobrança mensal recorrente conforme contrato.</strong></div><div class="billingItem"><span>Implantação</span><strong>${esc(d.implementationFee||'Conforme proposta')} — pagamento antecipado para início da implantação.</strong></div><div class="billingItem"><span>Sistema / software</span><strong>${esc(d.softwareRepasse||'Conforme contratação')}</strong></div></div>`;box.appendChild(wrap)}
function render(){
  document.querySelectorAll('.brandLogo,.footerLogo').forEach(img=>{img.src='/assets/fenix-logo-transparent.webp';img.onerror=()=>{img.src='/assets/fenix-symbol.png'}});
  setText('clientName',d.clientName);setText('clientName2',d.clientName);setText('date',d.date);setText('summary',d.businessSummary);setText('diagnosticPhrase',d.diagnosticPhrase);setHtml('operationalScope',list(d.operationalScope));setHtml('strategicScope',list(d.strategicScope));setText('monthlyFee',d.monthlyFee);setText('implementationFee',d.implementationFee);setText('softwareRepasse',d.softwareRepasse);setText('implementationSituation',d.implementationSituation);
  const pillars=['Controle','Previsibilidade','Decisão'];setHtml('pillars',pillars.map((p,i)=>`<div class="pillar"><b>${p}</b><p>${esc((d.painPoints||[])[i]||(d.objectives||[])[i]||'Informação estruturada para uma operação mais segura.')}</p></div>`).join(''));
  setHtml('techFlow',(d.technologyHighlights||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Rotinas claras e documentadas.','Menos tarefas repetitivas e mais consistência.','Apoio inteligente para leitura e organização de informações.','Base confiável para relatórios e decisões.'][i]||''}</p></div>`).join(''));
  setHtml('implFlow',(d.implementationSteps||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Levantamento do cenário e das prioridades.','Configuração de cadastros, regras e rotinas.','Saneamento e estruturação da base inicial.','Entrada em operação com calendário definido.'][i]||''}</p></div>`).join(''));
  const mets=[['Movimentos',d.monthlyMovements],['CNPJs',d.cnpjs],['Bancos',d.banks],['Cartões',d.cards],['Contratos/mês',d.contractsPerMonth],['Comissões/mês',d.commissionsPerMonth]];setHtml('metrics',mets.map(x=>`<div class="metric"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join(''));
  setHtml('conditions',(d.commercialConditions||[]).map(x=>`<li>${esc(x)}</li>`).join(''));addBillingSummary();setHtml('steps',(d.nextSteps||[]).map((x,i)=>`<div class="step"><h4>${esc(x)}</h4><p>${['Validação do escopo, premissas e condições comerciais.','Formalização do instrumento contratual e pagamentos iniciais.','Alinhamento inicial e preparação da operação.','Entrada em rotina com acompanhamento estruturado.'][i]||''}</p></div>`).join(''));
  const demo=q('demo');if(demo)demo.style.display=d.isDemo?'block':'none';
}
window.addEventListener('scroll',()=>{const el=q('topbtn');if(el)el.classList.toggle('show',scrollY>700)});window.addEventListener('DOMContentLoaded',render);window.printProposal=()=>window.print();window.goTop=()=>window.scrollTo({top:0,behavior:'smooth'});
