const fallbackData={isDemo:true,clientName:'Cliente Demonstração',date:'26 de agosto de 2026',businessSummary:'Operação com rotinas administrativo-financeiras que precisam de mais organização, previsibilidade e informação gerencial para apoiar decisões.',diagnosticPhrase:'Organizar a rotina, reduzir retrabalho e transformar dados financeiros em informação útil para a gestão.',painPoints:['Retrabalho em lançamentos e conciliações','Informações dispersas em sistemas e planilhas','Baixa previsibilidade de caixa'],objectives:['Organização','Previsibilidade','Decisão'],operationalScope:[{title:'Conciliação bancária diária',description:'Conferência de movimentações e apontamento de divergências.'},{title:'Contas a pagar',description:'Organização e acompanhamento de títulos e documentos.'},{title:'Contas a receber',description:'Acompanhamento de recebimentos e pendências.'},{title:'Agendamentos',description:'Preparação conforme autorização do cliente.'}],strategicScope:[{title:'Fluxo de caixa',description:'Visão prevista e realizada para apoio à decisão.'},{title:'Relatório mensal',description:'Síntese executiva da operação e dos principais pontos de atenção.'},{title:'Reunião estratégica',description:'Encontro periódico para leitura dos dados e alinhamento.'}],technologyHighlights:['Processos','Automação','IA','Dados'],implementationSteps:['Diagnóstico','Parametrização','Organização inicial','Início da operação'],monthlyMovements:'Até 300/mês',cnpjs:'1 CNPJ',banks:'2 bancos',cards:'Até 3 cartões',contractsPerMonth:'Conforme escopo',commissionsPerMonth:'Conforme escopo',implementationSituation:'Operação parcialmente organizada',monthlyFee:'R$ 1.600,00',implementationFee:'R$ 1.500,00',softwareRepasse:'Conforme contratação',commercialConditions:['Valores consideram as premissas apresentadas nesta proposta.','Mudanças relevantes de volume, estrutura ou escopo podem gerar revisão comercial mediante alinhamento prévio.','Serviços extraordinários e retrabalhos fora do escopo somente serão executados após autorização do cliente.'],nextSteps:['Aprovação da proposta','Contrato','Kickoff e implantação','Início da operação']};
const d=window.__FENIX_PROPOSAL_DATA__||fallbackData;
const q=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const setText=(id,v)=>{const el=q(id);if(el)el.textContent=v??''};
const setHtml=(id,v)=>{const el=q(id);if(el)el.innerHTML=v??''};
function list(items,cls='scopeItem'){return(items||[]).map(x=>typeof x==='string'?`<div class="${cls}"><strong>${esc(x)}</strong></div>`:`<div class="${cls}"><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p></div>`).join('')}
function isConfiar(){return String(d.clientName||'').toUpperCase().includes('CONFIAR IMÓVEIS')||String(d.clientName||'').toUpperCase().includes('CONFIAR IMOVEIS')}
function applyConfiarCommercials(){if(!isConfiar())return;
  d.monthlyFee='R$ 2.300,00';
  d.monthlyMovements='Até 500/mês — limite de 250 por CNPJ';
  d.banks='Até 2 contas bancárias incluídas';
  d.commercialConditions=[
    'Pacote contratual da operação: R$ 3.300,00/mês, considerando os 2 CNPJs e o escopo aprovado.',
    'Condição especial da parceria contábil: desconto de R$ 1.000,00/mês.',
    'Mensalidade final da parceria: R$ 2.300,00/mês, correspondente a R$ 1.150,00 por CNPJ/mês.',
    'Limite operacional: até 250 lançamentos financeiros por CNPJ por mês, totalizando até 500 lançamentos/mês para o grupo.',
    'O pacote contempla até 2 contas bancárias no grupo. A partir da 3ª conta bancária, será aplicado adicional de R$ 150,00/mês por conta.',
    'Implantação inicial: R$ 3.000,00, paga antecipadamente para início do projeto.',
    'Conta Azul: R$ 239,90/mês, pago à parte e de forma pré-paga; o primeiro pagamento é devido na assinatura do contrato.',
    'Ultrapassagens recorrentes de volume, inclusão de novos CNPJs, contas bancárias, filiais, cartões ou mudanças relevantes de escopo poderão gerar revisão comercial mediante alinhamento prévio.',
    'Serviços extraordinários, saneamentos adicionais e retrabalhos fora do escopo somente serão executados após autorização do cliente.',
    'A Fênix atua como apoio administrativo-financeiro; autorizações de pagamentos, movimentação de recursos e decisões permanecem com o cliente.'
  ];
}
function addBillingSummary(){const conditions=q('conditions');if(!conditions)return;const box=conditions.closest('.legalBox');if(!box||box.querySelector('.billingWrap'))return;const wrap=document.createElement('div');wrap.className='billingWrap';wrap.innerHTML=`<h4>Forma de cobrança</h4><div class="billingGrid"><div class="billingItem"><span>Mensalidade</span><strong>${esc(d.monthlyFee||'Conforme contrato')} — cobrança mensal recorrente conforme contrato.</strong></div><div class="billingItem"><span>Implantação</span><strong>${esc(d.implementationFee||'Conforme proposta')} — pagamento antecipado para início da implantação.</strong></div><div class="billingItem"><span>Sistema / software</span><strong>${esc(d.softwareRepasse||'Conforme contratação')}</strong></div>${isConfiar()?'<div class="billingItem"><span>Limite do pacote</span><strong>250 lançamentos por CNPJ/mês — até 500 lançamentos/mês no grupo.</strong></div><div class="billingItem"><span>Conta bancária adicional</span><strong>A partir da 3ª conta bancária do grupo: + R$ 150,00/mês por conta.</strong></div>':''}</div>`;box.appendChild(wrap)}
function applyConfiarVisuals(){if(!isConfiar())return;const lead=document.querySelector('#investimento .lead');if(lead)lead.textContent='O pacote contratual da operação é de R$ 3.300,00 mensais para os 2 CNPJs. Pela parceria contábil, aplicamos desconto de R$ 1.000,00, resultando em mensalidade final de R$ 2.300,00 — R$ 1.150,00 por CNPJ.';const value=document.querySelector('.priceValue');if(value)value.textContent='R$ 2.300,00';const base=document.querySelector('.priceBase');if(base)base.textContent='R$ 3.300,00';const disc=document.querySelector('.priceDiscount');if(disc)disc.textContent='− R$ 1.000,00/mês';const primary=document.querySelector('.pricePrimary .priceNote');if(primary)primary.textContent='Mensalidade final do grupo: R$ 1.150,00 por CNPJ/mês.';const detail=document.querySelector('.priceDetail');if(detail&&!detail.querySelector('.cnpjSplit')){const div=document.createElement('div');div.className='cnpjSplit';div.innerHTML='<span class="priceLabel" style="margin-top:22px">Distribuição por CNPJ</span><div class="priceDiscount">R$ 1.150,00 por CNPJ</div>';detail.appendChild(div)}}
function render(){
  applyConfiarCommercials();
  document.querySelectorAll('.brandLogo,.footerLogo').forEach(img=>{img.src='/assets/fenix-logo-transparent.webp';img.onerror=()=>{img.src='/assets/fenix-symbol.png'}});
  setText('clientName',d.clientName);setText('clientName2',d.clientName);setText('date',d.date);setText('summary',d.businessSummary);setText('diagnosticPhrase',d.diagnosticPhrase);setHtml('operationalScope',list(d.operationalScope));setHtml('strategicScope',list(d.strategicScope));setText('monthlyFee',d.monthlyFee);setText('implementationFee',d.implementationFee);setText('softwareRepasse',d.softwareRepasse);setText('implementationSituation',d.implementationSituation);
  const pillars=['Controle','Previsibilidade','Decisão'];setHtml('pillars',pillars.map((p,i)=>`<div class="pillar"><b>${p}</b><p>${esc((d.painPoints||[])[i]||(d.objectives||[])[i]||'Informação estruturada para uma operação mais segura.')}</p></div>`).join(''));
  setHtml('techFlow',(d.technologyHighlights||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Rotinas claras e documentadas.','Menos tarefas repetitivas e mais consistência.','Apoio inteligente para leitura e organização de informações.','Base confiável para relatórios e decisões.'][i]||''}</p></div>`).join(''));
  setHtml('implFlow',(d.implementationSteps||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Levantamento do cenário e das prioridades.','Configuração de cadastros, regras e rotinas.','Saneamento e estruturação da base inicial.','Entrada em operação com calendário definido.'][i]||''}</p></div>`).join(''));
  const mets=[['Lançamentos contratados',d.monthlyMovements],['CNPJs',d.cnpjs],['Contas bancárias',d.banks],['Cartões',d.cards],['Contratos/mês',d.contractsPerMonth],['Comissões/mês',d.commissionsPerMonth]];setHtml('metrics',mets.map(x=>`<div class="metric"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join(''));
  setHtml('conditions',(d.commercialConditions||[]).map(x=>`<li>${esc(x)}</li>`).join(''));addBillingSummary();applyConfiarVisuals();setHtml('steps',(d.nextSteps||[]).map((x,i)=>`<div class="step"><h4>${esc(x)}</h4><p>${['Validação do escopo, premissas e condições comerciais.','Formalização do instrumento contratual e pagamentos iniciais.','Alinhamento inicial e preparação da operação.','Entrada em rotina com acompanhamento estruturado.'][i]||''}</p></div>`).join(''));
  const demo=q('demo');if(demo)demo.style.display=d.isDemo?'block':'none';
}
window.addEventListener('scroll',()=>{const el=q('topbtn');if(el)el.classList.toggle('show',scrollY>700)});window.addEventListener('DOMContentLoaded',render);window.printProposal=()=>window.print();window.goTop=()=>window.scrollTo({top:0,behavior:'smooth'});
