const fallbackData={isDemo:true,clientName:'Cliente Demonstração',date:'26 de agosto de 2026',businessSummary:'Operação com rotinas administrativo-financeiras que precisam de mais organização, previsibilidade e informação gerencial para apoiar decisões.',diagnosticPhrase:'Organizar a rotina, reduzir retrabalho e transformar dados financeiros em informação útil para a gestão.',painPoints:['Retrabalho em lançamentos e conciliações','Informações dispersas em sistemas e planilhas','Baixa previsibilidade de caixa'],objectives:['Organização','Previsibilidade','Decisão'],operationalScope:[{title:'Conciliação bancária diária',description:'Conferência de movimentações e apontamento de divergências.'},{title:'Contas a pagar',description:'Organização e acompanhamento de títulos e documentos.'},{title:'Contas a receber',description:'Acompanhamento de recebimentos e pendências.'},{title:'Agendamentos',description:'Preparação conforme autorização do cliente.'}],strategicScope:[{title:'Fluxo de caixa',description:'Visão prevista e realizada para apoio à decisão.'},{title:'Relatório mensal',description:'Síntese executiva da operação e dos principais pontos de atenção.'},{title:'Reunião estratégica',description:'Encontro periódico para leitura dos dados e alinhamento.'}],technologyHighlights:['Processos','Automação','IA','Dados'],implementationSteps:['Diagnóstico','Parametrização','Organização inicial','Início da operação'],monthlyMovements:'Até 300/mês',cnpjs:'1 CNPJ',banks:'2 bancos',cards:'Até 3 cartões',contractsPerMonth:'Conforme escopo',commissionsPerMonth:'Conforme escopo',implementationSituation:'Operação parcialmente organizada',monthlyFee:'R$ 1.600,00',implementationFee:'R$ 1.500,00',softwareRepasse:'Conforme contratação',commercialConditions:['Valores consideram as premissas apresentadas nesta proposta.','Mudanças relevantes de volume, estrutura ou escopo podem gerar revisão comercial mediante alinhamento prévio.','Serviços extraordinários e retrabalhos fora do escopo somente serão executados após autorização do cliente.'],nextSteps:['Aprovação da proposta','Contrato','Kickoff e implantação','Início da operação']};
const d=window.__FENIX_PROPOSAL_DATA__||fallbackData;
const q=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function list(items,cls='scopeItem'){return(items||[]).map(x=>typeof x==='string'?`<div class="${cls}"><strong>${esc(x)}</strong></div>`:`<div class="${cls}"><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p></div>`).join('')}
function render(){q('clientName').textContent=d.clientName;q('clientName2').textContent=d.clientName;q('date').textContent=d.date;q('summary').textContent=d.businessSummary;q('diagnosticPhrase').textContent=d.diagnosticPhrase;q('operationalScope').innerHTML=list(d.operationalScope);q('strategicScope').innerHTML=list(d.strategicScope);q('monthlyFee').textContent=d.monthlyFee;q('implementationFee').textContent=d.implementationFee;q('softwareRepasse').textContent=d.softwareRepasse;q('implementationSituation').textContent=d.implementationSituation;
const pillars=['Controle','Previsibilidade','Decisão'];q('pillars').innerHTML=pillars.map((p,i)=>`<div class="pillar"><span class="eyebrow">0${i+1}</span><b>${p}</b><p>${esc((d.painPoints||[])[i]||(d.objectives||[])[i]||'Informação estruturada para uma operação mais segura.')}</p></div>`).join('');
q('techFlow').innerHTML=(d.technologyHighlights||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Rotinas claras e documentadas.','Menos tarefas repetitivas e mais consistência.','Apoio inteligente para leitura e organização de informações.','Base confiável para relatórios e decisões.'][i]||''}</p></div>`).join('');
q('implFlow').innerHTML=(d.implementationSteps||[]).map((x,i)=>`<div class="flowStep"><b>${esc(x)}</b><p>${['Levantamento do cenário e das prioridades.','Configuração de cadastros, regras e rotinas.','Saneamento e estruturação da base inicial.','Entrada em operação com calendário definido.'][i]||''}</p></div>`).join('');
const mets=[['Movimentos',d.monthlyMovements],['CNPJs',d.cnpjs],['Bancos',d.banks],['Cartões',d.cards],['Contratos/mês',d.contractsPerMonth],['Comissões/mês',d.commissionsPerMonth]];q('metrics').innerHTML=mets.map(x=>`<div class="metric"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('');
q('conditions').innerHTML=(d.commercialConditions||[]).map(x=>`<li>${esc(x)}</li>`).join('');q('steps').innerHTML=(d.nextSteps||[]).map((x,i)=>`<div class="step"><div class="n">0${i+1}</div><h4>${esc(x)}</h4><p>${['Validação do escopo, premissas e condições comerciais.','Formalização do instrumento contratual.','Alinhamento inicial e preparação da operação.','Entrada em rotina com acompanhamento estruturado.'][i]||''}</p></div>`).join('');
q('demo').style.display=d.isDemo?'block':'none';}
window.addEventListener('scroll',()=>q('topbtn').classList.toggle('show',scrollY>700));window.addEventListener('DOMContentLoaded',render);window.printProposal=()=>window.print();window.goTop=()=>window.scrollTo({top:0,behavior:'smooth'});
